AWSTemplateFormatVersion: 2010-09-09

Description: codebuild project for aws codepipeline poc

Parameters:
  CodeBuildBucketName:
    Type: String
    Description: s3 bucket for code build logs

  DockerUsername:
    Type: String
    Description: username for hub.docker
    Default: seanturner026

  DockerPassword:
    Type: String
    Description: password for hub.docker
    Default: /codebuild/docker/username

  Environment:
    Type: String
    Description: environment
    AllowedValues:
      - dev
      - prod
    Default: dev

  Vpc:
    Type: AWS::EC2::VPC::Id

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet3:
    Type: AWS::EC2::Subnet::Id

  CodeBuildSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join
        - ""
        - - "code-build-role-"
          - !Ref Environment
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: "codebuild.amazonaws.com"
          Action: "sts:AssumeRole"

  CodeBuildPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Join
        - ""
        - - "code-build-policy-"
          - !Ref Environment
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - apigateway:GET
            - apigateway:POST
            - apigateway:PUT
            - apigateway:DELETE
            - codebuild:*
            - cloudformation:List*
            - cloudformation:Get*
            - cloudformation:PreviewStackUpdate
            - cloudformation:ValidateTemplate
            - cloudformation:CreateStack
            - cloudformation:CreateUploadBucket
            - cloudformation:DeleteStack
            - cloudformation:Describe*
            - cloudformation:UpdateStack
            - cloudwatch:GetMetricStatistics
            - dynamodb:*
            - ec2:DeleteNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeSecurityGroups
            - ec2:DescribeSubnets
            - ec2:DescribeVpcs
            - events:Put*
            - events:Remove*
            - events:Delete*
            - lambda:Get*
            - iam:CreateRole
            - iam:GetRole
            - iam:DeleteRolePolicy
            - iam:DeleteRole
            - iam:PassRole
            - iam:PutRolePolicy
            - kinesis:*
            - lambda:List*
            - lambda:CreateFunction
            - lambda:AddPermission
            - lambda:CreateAlias
            - lambda:DeleteFunction
            - lambda:InvokeFunction
            - lambda:PublishVersion
            - lambda:RemovePermission
            - lambda:Update*
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DeleteLogGroup
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:FilterLogEvents
            - logs:PutLogEvents
            - s3:CreateBucket
            - s3:DeleteBucket
            - s3:DeleteObject
            - s3:GetObject
            - s3:ListBucket
            - s3:ListBucketVersions
            - s3:PutObject
            - "*"
          Resource: "*"
      Roles:
        - !Ref CodeBuildRole

  BuildPushJob:
    Type: "AWS::CodeBuild::Project"
    DependsOn:
      - CodeBuildPolicy
      - CodeBuildRole
    Properties:
      Name: build-push-job
      Description: build and push docker containers to hub.docker
      ServiceRole: !Ref CodeBuildRole
      VpcConfig:
        VpcId: !Ref Vpc
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroupId
        Subnets:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
          - !Ref PrivateSubnet3
      TimeoutInMinutes: 5
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            pre_build:
              commands:
                - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2& > /dev/null
                - timeout 15 sh -c "until docker info > /dev/null; do echo .; sleep 1; done"
            build:
              commands:
                - bash aws/scripts/build-push.sh
      Environment:
        Type: "LINUX_CONTAINER"
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Type: PLAINTEXT
            Value: !Ref Environment
          - Name: DOCKER_USERNAME
            Type: PLAINTEXT
            Value: !Ref DockerUsername
          - Name: DOCKER_PASSWORD
            Type: PARAMETER_STORE
            Value: !Ref DockerPassword
        Image: seanturner026/custom-ci-images:codebuild
        PrivilegedMode: true
      LogsConfig:
        S3Logs:
          EncryptionDisabled: true
          Location: !Ref CodeBuildBucketName
          Status: ENABLED
      Artifacts:
        Type: CODEPIPELINE

Outputs:
  BuildPushJob:
    Description: codebuild job for building and pushing docker images
    Value: !Ref BuildPushJob
