AWSTemplateFormatVersion: 2010-09-09

Description: codebuild project for aws codepipeline poc

Parameters:
  CodeBuildBucketName:
    Type: String
    Description: s3 bucket for code build logs

  CodeBuildRole:
    Type: String
    Description: iam role for code build project

  DockerUsername:
    Type: String
    Description: username for hub.docker

  DockerPassword:
    Type: String
    Description: password for hub.docker

  Environment:
    Type: String
    Description: environment
    AllowedValues:
      - dev
      - prod

  Vpc:
    Type: AWS::EC2::VPC::Id

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet3:
    Type: AWS::EC2::Subnet::Id

  CodeBuildSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  BuildPushJob:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: build-push-job
      Description: build and push docker containers to hub.docker
      ServiceRole: !Ref CodeBuildRole
      VpcConfig:
        VpcId: !Ref Vpc
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroupId
        Subnets:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
          - !Ref PrivateSubnet3
      TimeoutInMinutes: 5
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            pre_build:
              commands:
                - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2& > /dev/null
                - timeout 15 sh -c "until docker info > /dev/null; do echo .; sleep 1; done"
            build:
              commands:
                - bash aws/scripts/build-push.sh
      Environment:
        Type: "LINUX_CONTAINER"
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Type: PLAINTEXT
            Value: !Ref Environment
          - Name: DOCKER_USERNAME
            Type: PLAINTEXT
            Value: !Ref DockerUsername
          - Name: DOCKER_PASSWORD
            Type: PARAMETER_STORE
            Value: !Ref DockerPassword
        Image: seanturner026/custom-ci-images:codebuild
        PrivilegedMode: true
      LogsConfig:
        S3Logs:
          EncryptionDisabled: true
          Location: !Ref CodeBuildBucketName
          Status: ENABLED
      Artifacts:
        Type: CODEPIPELINE

Outputs:
  BuildPushJob:
    Description: codebuild job for building and pushing docker images
    Value: !Ref BuildPushJob
