AWSTemplateFormatVersion: 2010-09-09

Description: s3 bucket for aws codepipeline poc

Resources:
  CodePiplineBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "sean-poc-codepipeline-bucket"
  CodeBuildBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "sean-poc-codebuild-bucket"

Outputs:
  CodePipelineBucketName:
    Description: S3 bucket name for code pipeline
    Value: !Ref CodePiplineBucket
  CodeBuildBucketName:
    Description: S3 bucket name for code build
    Value: !Ref CodeBuildBucket
