AWSTemplateFormatVersion: 2010-09-09

Description: codebuild project for aws codepipeline poc

Parameters:
  CodeBuildBucketName:
    Type: String
    Description: s3 bucket for code build logs

  CodeBuildRole:
    Type: String
    Description: iam role for code build project

  DockerUsername:
    Type: String
    Description: username for hub.docker

  DockerPassword:
    Type: String
    Description: password for hub.docker

  Environment:
    Type: String
    Description: environment
    AllowedValues:
      - dev
      - prod

  Vpc:
    Type: AWS::EC2::VPC::Id

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id

  PrivateSubnet3:
    Type: AWS::EC2::Subnet::Id

  CodeBuildSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  BuildPushJob:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: build-push-job
      Description: build and push docker containers to hub.docker
      ServiceRole: !Ref CodeBuildRole
      VpcConfig:
        VpcId: !Ref Vpc
        SecurityGroupIds:
          - !Ref CodeBuildSecurityGroupId
        Subnets:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
          - !Ref PrivateSubnet3
      TimeoutInMinutes: 5
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Join
          - ""
          - - "cloudformation/buildspecs/buildspec-"
            - !Ref Environment
            - ".yaml"
      Environment:
        Type: "LINUX_CONTAINER"
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Type: PLAINTEXT
            Value: !Ref Environment
          - Name: DOCKER_USERNAME
            Type: PLAINTEXT
            Value: !Ref DockerUsername
          - Name: DOCKER_PASSWORD
            Type: PARAMETER_STORE
            Value: !Ref DockerPassword
        Image: seanturner026/custom-ci-images:codebuild
        PrivilegedMode: true
      Cache:
        Type: S3
        Location: !Join
          - ""
          - - !Ref CodeBuildBucketName
            - "/cache"
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      LogsConfig:
        S3Logs:
          EncryptionDisabled: true
          Location: !Join
            - ""
            - - !Ref CodeBuildBucketName
              - "/logs"
          Status: ENABLED
      Artifacts:
        Type: CODEPIPELINE

Outputs:
  BuildPushJob:
    Description: codebuild job for building and pushing docker images
    Value: !Ref BuildPushJob
