AWSTemplateFormatVersion: 2010-09-09

Description: root template for codepipeline poc

Parameters:

  CodeBuildBucketName:
    Description: name of bucket for code build logging
    Type: String
    Default: sean-poc-codebuild-bucket

  CodePipelineBucketName:
    Description: name of bucket for code pipeline artifacts
    Type: String
    Default: sean-poc-codepipeline-bucket

  DockerUsername:
    Type: String
    Description: username for hub.docker
    Default: seanturner026

  DockerPassword:
    Type: String
    Description: password for hub.docker
    Default: /codebuild/docker/password

  Environment:
    Type: String
    Description: environment
    AllowedValues:
      - dev
      - prod
    Default: dev

  GithubRepository:
    Type: String
    Description: github repository
    Default: aws-codepipeline-poc

  GithubBranch:
    Type: String
    Description: github branch
    Default: master

  GithubOwner:
    Type: String
    Description: github owner
    Default: SeanTurner026

  GithubToken:
    Type: String
    Description: github token for codepipeline
    NoEcho: true

  VpcName:
    Description: name of the vpc
    Type: String
    Default: sandbox

Mappings:
  SubnetConfig:
    GlobalCidr:
      cidr: 10.0.0.0/18
    PublicCidr1:
      cidr: 10.0.0.0/20
    PrivateCidr1:
      cidr: 10.0.16.0/20
    PrivateCidr2:
      cidr: 10.0.32.0/20
    PrivateCidr3:
      cidr: 10.0.48.0/20

  AvailabilityZones:
    az1:
      az: us-east-1a
    az2:
      az: us-east-1b
    az3:
      az: us-east-1c

Resources:

  IamCodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Environment: !Ref Environment
      TemplateURL: resources/iam_codebuild.yaml

  IamCodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Environment: !Ref Environment
      TemplateURL: resources/iam_codepipeline.yaml

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CodeBuildBucketName: !Ref CodeBuildBucketName
        CodePipelineBucketName: !Ref CodePipelineBucketName
      TemplateURL: resources/s3.yaml

  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CidrBlock: !FindInMap [SubnetConfig, GlobalCidr, cidr]

        PrivateSubnet1AZ: !FindInMap [AvailabilityZones, az1, az]
        PrivateSubnet1Cidr: !FindInMap [SubnetConfig, PrivateCidr1, cidr]

        PrivateSubnet2AZ: !FindInMap [AvailabilityZones, az2, az]
        PrivateSubnet2Cidr: !FindInMap [SubnetConfig, PrivateCidr2, cidr]

        PrivateSubnet3AZ: !FindInMap [AvailabilityZones, az3, az]
        PrivateSubnet3Cidr: !FindInMap [SubnetConfig, PrivateCidr3, cidr]

        PublicSubnetAZ: !FindInMap [AvailabilityZones, az1, az]
        PublicSubnetCidr: !FindInMap [SubnetConfig, PublicCidr1, cidr]

        VpcName: !Ref VpcName
      TemplateURL: resources/vpc.yaml

  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IamCodeBuildStack
      - S3Stack
      - VpcStack
    Properties:
      Parameters:
        DockerUsername: !Ref DockerUsername
        DockerPassword: !Ref DockerPassword

        Environment: !Ref Environment

        CodeBuildRole: !GetAtt IamCodeBuildStack.Outputs.CodeBuildRole
        CodeBuildBucketName: !GetAtt S3Stack.Outputs.CodeBuildBucketName
        CodeBuildSecurityGroupId: !GetAtt VpcStack.Outputs.CodeBuildSecurityGroupId

        PrivateSubnet1: !GetAtt VpcStack.Outputs.PrivateSubnetId1
        PrivateSubnet2: !GetAtt VpcStack.Outputs.PrivateSubnetId2
        PrivateSubnet3: !GetAtt VpcStack.Outputs.PrivateSubnetId3

        Vpc: !GetAtt VpcStack.Outputs.VpcId
      TemplateURL: resources/codebuild.yaml

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IamCodePipelineStack
      - CodeBuildStack
      - S3Stack
    Properties:
      Parameters:
        Environment: !Ref Environment

        GithubRepository: !Ref GithubRepository
        GithubBranch: !Ref GithubBranch
        GithubOwner: !Ref GithubOwner
        GithubToken: !Ref GithubToken

        BuildPushJob: !GetAtt CodeBuildStack.Outputs.BuildPushJob

        CodePipelineRole: !GetAtt IamCodePipelineStack.Outputs.CodePipelineRole
        CodePipelineBucketName: !GetAtt S3Stack.Outputs.CodePipelineBucketName
      TemplateURL: resources/codepipeline.yaml
