AWSTemplateFormatVersion: 2010-09-09

Description: root template for codepipeline poc

Parameters:
  VpcName:
    Description: name of the vpc
    Type: String
    Default: sandbox

  DockerUsername:
    Type: String
    Description: username for hub.docker
    Default: seanturner026

  DockerPassword:
    Type: String
    Description: password for hub.docker
    Default: /codebuild/docker/password

  Environment:
    Type: String
    Description: environment
    AllowedValues:
      - dev
      - prod
    Default: dev

  GithubRepository:
    Type: String
    Description: github repository
    Default: aws-codepipeline-poc

  GithubBranch:
    Type: String
    Description: github branch
    Default: master

  GithubOwner:
    Type: String
    Description: github owner
    Default: SeanTurner026

  GithubToken:
    Type: String
    Description: github token for codepipeline
    NoEcho: true

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcName: !Ref VpcName
      TemplateURL: resources/vpc.yaml

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: resources/s3.yaml

  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Environment: !Ref Environment
        DockerUsername: !Ref DockerUsername
        DockerPassword: !Ref DockerPassword
      TemplateURL: resources/codebuild.yaml

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Environment: !Ref Environment
        GithubRepository: !Ref GithubRepository
        GithubBranch: !Ref GithubBranch
        GithubOwner: !Ref GithubOwner
        GithubToken: !Ref GithubToken
      TemplateURL: resources/codepipeline.yaml
